apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: danielma911/daniel-web
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: 'danielma911/daniel-web:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: 'danielma911/daniel-web:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: daniel-web
        chartPath: charts/daniel-web
        setValueTemplates:
          image.repository: 'danielma911/daniel-web'
          image.tag: '{{.DIGEST_HEX}}'
